// <auto-generated />
namespace it.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addbairroemcandidatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbairroemcandidatos));
        
        string IMigrationMetadata.Id
        {
            get { return "201406070201582_add bairro em candidatos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
