// <auto-generated />
namespace it.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mudarbirthdateparadatanasceadddependentesnoscandidatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudarbirthdateparadatanasceadddependentesnoscandidatos));
        
        string IMigrationMetadata.Id
        {
            get { return "201406070150016_mudar birthdate para datanasc e add dependentes nos candidatos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
